function [ img_blend ] = poisson_blend( feat, param )
%poisson_blend reconstructs an image from the gradient feature data.
%   (INPUT)     feat: input feature data
%               param (optional): the parameters generated by
%               build_poi_param
%               ep (optional): constraint parameter. small
%               lambda (optional): small positive number to avoid
%               singularity.

ep = 1e-8;
lambda = 1e-12;

s = [size(feat, 1), size(feat, 2), size(feat, 3)];
% sk = size(param);

Fh = ( feat(:,:,:,2) + circshift(feat(:,:,:,4),[0,-1])) / 2;
Fv = ( feat(:,:,:,3) + circshift(feat(:,:,:,5),[-1,0])) / 2;
L = circshift(Fh,[0,1]) + circshift(Fv,[1,0]) - Fh - Fv;

paramep = param + ep;
paramep(paramep >= 0 & paramep < lambda) = lambda;
paramep(paramep < 0 & paramep > -lambda) = -lambda;

img_blend = zeros(s);
for i=1:s(3)
    Xdct = dct2(feat(:,:,i));
    Ydct = ( dct2(L(:,:,i)) + ep * Xdct  ) ./ paramep;
    img_blend(:,:,i) = idct2(Ydct);
end

end

